apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: shoutan-course
spec:
  selector:
    matchLabels:
      app: shoutan-course
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: shoutan-course
        tier: frontend
    spec:
      containers:
      - name: game-server
        image: registry-vpc.cn-beijing.aliyuncs.com/shoutan/shoutan-course:0.3
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: service-config
        env:
          - name: API_SERVER_URL
            value: 'http://course.shoutanwq.com'
      imagePullSecrets:
      - name: aliyun-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shoutan-course
  labels:
    app: shoutan-course
    tier: frontend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: shoutan-course
    tier: frontend
